### PR TITLE
added jump-to-char

### PR DESCRIPTION
**Pull request by haennes**
Great Project :)
I am planning on adding another bunch of plugins in ~ 12 days, you can leave this open and merge once or I will open a PR for each package.

Fails due to lua script failing: (probably due to this commit: yazi-rs/plugins@3783ea0)
- diff
`
Micro plugin failed:
runtime error: [string "/build/source/yazi-plugin/src/isolate/entry.r..."]:34: attempt to call a nil value (field 'clipboard')
stack traceback:
	[string "/build/source/yazi-plugin/src/isolate/entry.r..."]:34: in function <[string "/build/source/yazi-plugin/src/isolate/entry.r..."]:21>
`

### CODE REVIEW

**Comment by lordkekz** [comment]
Thanks a lot! I'll leave this PR open so you can focus on adding the plugins.

**Comment by haennes** [comment]
the others should work. maybe we should consider refactoring the plugins in the [yazi-rs/plugins](https://github.com/yazi-rs/plugins) into a common file :thinking:

**Comment by lordkekz** [comment]
> maybe we should consider refactoring the plugins in the [yazi-rs/plugins](https://github.com/yazi-rs/plugins) into a common file 🤔

Yeah, you can create a `plugins/default.nix` and return an attribute set of packages and it should work after https://github.com/lordkekz/nix-yazi-plugins/commit/2f9e4a29d80746555c73677d57eb27d85d079d0b (I just fixed it).

> could be that diff works on yazi master, havent tried out

I have also yet to test things with the unstable yazi. I want to support the latest release and but also start updating things for the unstable version, so I have created a separate branch for plugins compatible with v0.2.5. Let's target this MR at the unstable version (`main` branch) and later cherry-pick the plugins that work with the release version.

**Comment by haennes** [comment]
> Yeah, you can create a `plugins/default.nix` and return an attribute set of packages and it should work after [2f9e4a2](https://github.com/lordkekz/nix-yazi-plugins/commit/2f9e4a29d80746555c73677d57eb27d85d079d0b) (I just fixed it).

great, will use a wrapper function with defaults to be able to update the plugins individually if upstream breaks only one (for nixos)


> I have also yet to test things with the unstable yazi. I want to support the latest release and but also start updating things for the unstable version, so I have created a separate branch for plugins compatible with v0.2.5. Let's target this MR at the unstable version (`main` branch) and later cherry-pick the plugins that work with the release version.

I actually specifically downgraded to the commits that work on the stable release (so we should just merge this one into the v0.2.5 branch)
I will open another pr for the unstable / main branch

**Comment by haennes** [comment]
Sorry completely forgot about it as it works on my machine. Will take a look at this in the near future

**Comment by lordkekz** [comment]
Yeah, same. No problem tho. I'm just putting this in the old branch so I can start a new branch for the latest release.
Feel free to open another MR! :)

**Pull request merged**
